version: '3.8'

services:
  db:
    image: postgres:15
    container_name: db_goods_prediction
    restart: always
    environment:
      TZ: Asia/Ho_Chi_Minh
      POSTGRES_DB: db_goods_prediction
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data #bên trái : là volumes bên ngoài, bên phải là container. thì volumes bên dưới nó phải trùng với cái bên trái
    ports:
      - "5434:5432" # Sử dụng biến môi trường hoặc mặc định 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d db_goods_prediction"]
      interval: 10s
      timeout: 5s
      retries: 5
  backend:
    build: ./backend
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/db_goods_prediction
    networks:
      - app-network
    ports:
      - "5055:5055"
  frontend:
    build: ./frontend
    restart: always
    ports:
      - "3000:80"
    networks:
      - app-network
volumes:
  postgres_data:

networks:
  app-network: