version: '3.8'

services:
  db:
    image: postgres:15
    container_name: aptis_postgres_db
    restart: always
    environment:
      POSTGRES_DB: db_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data #bên trái : là volumes bên ngoài, bên phải là container. thì volumes bên dưới nó phải trùng với cái bên trái
    ports:
      - "5432:5432" # Sử dụng biến môi trường hoặc mặc định 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  postgres_data: